# --- Backend y Rendimiento ---
backend = "glx";
vsync = true;
glx-no-stencil = true;
glx-no-rebind-pixmap = true;
use-damage = true;


shadow-exclude = [
    "name = 'Idesk'",
    "class_g = 'Idesk'",
    "_NET_WM_WINDOW_TYPE@:a *= '_NET_WM_WINDOW_TYPE_DESKTOP'"
];